
***********************************************************************
 Starting job:

    Name:              MixedHess
    ID:                400831
    Hostname:          n029
    Working directory: /home/vulcan/mel64643/bin/MixedHessian/TESTS/1_H2O/Disps

    Submitted using:   MixedHessian 
***********************************************************************
module load  psi4-master-intel-16.0.1-avducsgnonqrcpftiesq432gagal6y7r
Traceback (most recent call last):
  File "/opt/psi/4/master/bin/psi4", line 331, in <module>
    exec(content)
  File "<string>", line 35, in <module>
  File "/opt/psi/4/master/lib/psi4/driver/driver.py", line 570, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/opt/psi/4/master/lib/psi4/driver/procrouting/proc.py", line 944, in select_ccsd_t_
    return func(name, **kwargs)
  File "/opt/psi/4/master/lib/psi4/driver/procrouting/proc.py", line 2557, in run_ccenergy
    ref_wfn = scf_helper(name, **kwargs)  # C1 certified
  File "/opt/psi/4/master/lib/psi4/driver/procrouting/proc.py", line 1527, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/opt/psi/4/master/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/opt/psi/4/master/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()

RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /tmp/psi4/psi4/psi4/src/psi4/libpsio/error.cc on line: 134
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


Printing out the relevant lines from the Psithon --> Python processed input file:
    core.set_global_option("REFERENCE", "rhf")
    core.set_global_option("E_CONVERGENCE", 10)
    core.set_global_option("D_CONVERGENCE", 10)
    core.set_global_option("R_CONVERGENCE", 8)
    core.set_global_option("MAXITER", 300)
--> energy('ccsd(t)')


!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: PSIO Error                                                          !
! Error occurred in file: /tmp/psi4/psi4/psi4/src/psi4/libpsio/error.cc on line:   !
!     134                                                                          !
! The most recent 5 function calls were:                                           !
! psi::PSIO::open(unsigned long, int)                                              !
!                                                                                  !
!----------------------------------------------------------------------------------!

